import api from '../api/client'

export const login = (payload) => api.post('/auth/login', payload)
export const me = () => api.get('/auth/me')
export const logout = () => api.post('/auth/logout')
export const forgotPassword = (payload) => api.post('/auth/forgot-password', payload)
export const verifyForgotOtp = (payload) => api.post('/auth/verify-forgot-otp', payload)
export const resetPassword = (payload) => api.post('/auth/reset-password', payload)
export const getAnalytics = () => api.get('/admin/analytics')
export const getSkillsStatistics = () => api.get('/admin/skills-statistics')
export const getUsers = (params) => api.get('/admin/users', { params })
export const deleteUser = (userId) => api.delete(`/admin/users/${userId}`)
export const getAuditLogs = (params) => api.get('/admin/audit-logs', { params })
export const getAIUsage = () => api.get('/admin/ai-usage')
export const getStorageUsage = () => api.get('/admin/storage-usage')
