import api from '../api/client'

export const login = (payload) => api.post('/auth/login', payload)
export const me = () => api.get('/auth/me')
export const logout = () => api.post('/auth/logout')
export const forgotPassword = (payload) => api.post('/auth/forgot-password', payload)
export const verifyForgotOtp = (payload) => api.post('/auth/verify-forgot-otp', payload)
export const resetPassword = (payload) => api.post('/auth/reset-password', payload)
export const getAnalytics = () => api.get('/admin/analytics')
export const getSkillsStatistics = () => api.get('/admin/skills-statistics')
export const getUsers = (params) => api.get('/admin/users', { params })
export const deleteUser = (userId) => api.delete(`/admin/users/${userId}`)
export const updateUser = (userId, payload) => api.put(`/admin/users/${userId}`, payload)
export const toggleUserStatus = (userId) => api.patch(`/admin/users/${userId}/status`)
export const verifyUserEmail = (userId) => api.patch(`/admin/users/${userId}/verify-email`)
export const resetUserPassword = (userId, payload) => api.post(`/admin/users/${userId}/reset-password`, payload)
export const getAuditLogs = (params) => api.get('/admin/audit-logs', { params })
export const getAIUsage = () => api.get('/admin/ai-usage')
export const getStorageUsage = () => api.get('/admin/storage-usage')

export const getSystemSettings = () => api.get('/admin/settings')
export const updateSystemSettings = (payload) => api.put('/admin/settings', payload)

export const getSkillsList = (params) => api.get('/admin/content/skills', { params })
export const deleteSkillAdmin = (id) => api.delete(`/admin/content/skills/${id}`)
export const getTopicsList = (params) => api.get('/admin/content/topics', { params })
export const deleteTopicAdmin = (id) => api.delete(`/admin/content/topics/${id}`)
export const getLogsList = (params) => api.get('/admin/content/logs', { params })
export const deleteLogAdmin = (id) => api.delete(`/admin/content/logs/${id}`)

export const getUploadedFilesList = () => api.get('/admin/files')
export const deleteFileAdmin = (payload) => api.post('/admin/files/delete', payload)
export const getLogFileContent = (params) => api.get('/admin/logs/view', { params })
